Traceback (most recent call last):
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aleksandrtusnin/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Num_of_photons = np.sum(np.abs((map2d[:,:])/(Num_of_modes))**2,axis=1)
fig = plt.figure(frameon=False,dpi=150)
ax = fig.add_subplot(1,1,1)
ax.plot(dOm/2/np.pi/1e9,Num_of_photons)
ax.set_xlabel('Laser detuning (GHz)')
ax.set_ylabel('Number of photons')
ax.grid(True)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/sn/qf84cb8n2jn9khwk0csmq2l80000gq/T/ipykernel_61222/1523350399.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mNum_of_photons[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0msum[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mabs[0m[0;34m([0m[0;34m([0m[0mmap2d[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;34m:[0m[0;34m][0m[0;34m)[0m[0;34m/[0m[0;34m([0m[0mNum_of_modes[0m[0;34m)[0m[0;34m)[0m[0;34m**[0m[0;36m2[0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mframeon[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m[0mdpi[0m[0;34m=[0m[0;36m150[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0max[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0madd_subplot[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mdOm[0m[0;34m/[0m[0;36m2[0m[0;34m/[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m/[0m[0;36m1e9[0m[0;34m,[0m[0mNum_of_photons[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0max[0m[0;34m.[0m[0mset_xlabel[0m[0;34m([0m[0;34m'Laser detuning (GHz)'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'map2d' is not defined
NameError: name 'map2d' is not defined

